<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.nifi</groupId>
        <artifactId>nifi-standard-services-api-bom</artifactId>
        <version>2.5.0-SNAPSHOT</version>
        <relativePath>../nifi-standard-services-api-bom</relativePath>
    </parent>

    <artifactId>nifi-daffodil-bundle</artifactId>
    <packaging>pom</packaging>

    <description>
        A NiFi processor bundle leveraging Apache Daffodil to dynamically parse and generate complex data formats (e.g., fixed-width text, binary, EDI) using DFDL schemas.
        Converts between raw data and structured formats (XML/JSON) without custom code, enabling seamless integration with NiFi dataflows.
    </description>

    <modules>
        <module>nifi-daffodil-processors</module>
        <module>nifi-daffodil-nar</module>
    </modules>
</project>